In [51]:
import numpy as np

#USER-USER Collaborative filtering example

M = [[1,3,5,4],[2,1,1,2],[1,3,4,4]]
N = np.array(M)
#correlations
C = np.corrcoef(N)
#averages
avgs = N.mean(axis=1)
#predictions for user 0 using users 1,2
i=0
j=1
k=2
print(avgs[i]+((N[j,:]-avgs[j])*C[i,j]+(N[k,:]-avgs[k])*C[i,k])/(abs(C[i,j])+abs(C[i,k])))
#predictions for user 1 using users 0,2
i=1
j=0
k=2
print(avgs[i]+((N[j,:]-avgs[j])*C[i,j]+(N[k,:]-avgs[k])*C[i,k])/(abs(C[i,j])+abs(C[i,k])))

#predictions for user 2 using users 0,1
i=2
j=0
k=1
print(avgs[i]+((N[j,:]-avgs[j])*C[i,j]+(N[k,:]-avgs[k])*C[i,k])/(abs(C[i,j])+abs(C[i,k])))




[ 1.76632291  3.42210764  4.07789236  3.73367709]
[ 3.63849829  1.63849829  0.08450514  0.63849829]
[ 1.26983823  2.97278781  4.37868698  3.37868698]


In [23]:
avgs

array([ 3.25,  1.5 ,  3.  ])

In [2]:
import numpy as np
#ITEM-ITEM Collaborative filtering example

M = [[1,3,5,4],[2,1,1,2],[1,3,4,4]]
N = np.array(M)
#Item correlations
I = np.transpose(N)
C = np.corrcoef(I)

#Predictions for item-0 using items 1,2,3
i=0
j=1
k=2
m=3
print((C[i,j]*I[j,:]+C[i,k]*I[k,:]+C[i,m]*I[m,:])/(abs(C[i,j])+abs(C[i,k])+abs(C[i,m])))

#Predictions for item-1 using items 0,2,3
i=1
j=0
k=2
m=3
print((C[i,j]*I[j,:]+C[i,k]*I[k,:]+C[i,m]*I[m,:])/(abs(C[i,j])+abs(C[i,k])+abs(C[i,m])))

#Predictions for item-2 using items 0,1,3
i=2
j=0
k=1
m=3
print((C[i,j]*I[j,:]+C[i,k]*I[k,:]+C[i,m]*I[m,:])/(abs(C[i,j])+abs(C[i,k])+abs(C[i,m])))

#Predictions for item-3 using items 0,1,2
i=3
j=0
k=1
m=2
print((C[i,j]*I[j,:]+C[i,k]*I[k,:]+C[i,m]*I[m,:])/(abs(C[i,j])+abs(C[i,k])+abs(C[i,m])))




[[1 3 5 4]
 [2 1 1 2]
 [1 3 4 4]]
[-3.99014562 -1.33661813 -3.66338187]
[2.64367311 0.32676375 2.31690937]
[2.         0.33333333 2.        ]
[ 2.30705499 -0.00985438  1.98029124]
