In [42]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.metrics.pairwise import cosine_similarity
import scipy

In [43]:
# load dataset
columns = ['userID','movieID','Rating']
user_movie_dataset = pd.read_csv('exampledataset/data_test.txt', delimiter=',', names=columns)
user_movie_dataset

userID  movieID  Rating
0       1        1       2
1       1        3       3
2       2        1       5
3       2        2       2
4       3        1       3
5       3        2       3
6       3        3       1
7       4        2       2
8       4        3       2

In [44]:
# Step 1: make user-movie matrix
user_movie_mat = user_movie_dataset.pivot(index='userID', columns='movieID', values='Rating')
user_movie_mat.fillna(0, inplace=True)
user_movie_mat

movieID    1    2    3
userID                
1        2.0  0.0  3.0
2        5.0  2.0  0.0
3        3.0  3.0  1.0
4        0.0  2.0  2.0

In [45]:
# Step 2: Item-item similarity matrix using cosine similarity
n_users, n_movies = user_movie_mat.shape
similarity_mat = np.zeros((n_movies, n_movies))
## calculate cosine similarity
for movie1 in range(n_movies):
    for movie2 in range(n_movies):
        if np.count_nonzero(user_movie_mat.iloc[:, movie1]) and np.count_nonzero(user_movie_mat.iloc[:, movie2]):
            similarity_mat[movie1][movie2] = 1-scipy.spatial.distance.cosine(user_movie_mat.iloc[:, movie1],user_movie_mat.iloc[:, movie2])

similarity_mat

array([[1.        , 0.747545  , 0.39019949],
       [0.747545  , 1.        , 0.45374261],
       [0.39019949, 0.45374261, 1.        ]])

In [46]:
cosin_sim = cosine_similarity(user_movie_mat.T, user_movie_mat.T)
cosin_sim

array([[1.        , 0.747545  , 0.39019949],
       [0.747545  , 1.        , 0.45374261],
       [0.39019949, 0.45374261, 1.        ]])

In [50]:
def predict_rating(user_id, movie_id):
    print(user_movie_mat.iloc[user_id, :])
    print(cosin_sim[:, movie_id].T)
    rating = np.sum(np.dot(user_movie_mat.iloc[user_id, :],similarity_mat[:, movie_id]))/(np.sum(similarity_mat[:, movie_id])-1)
    print(rating)

In [51]:
predict_rating(3,0)

movieID
1    0.0
2    2.0
3    2.0
Name: 4, dtype: float64
[1.         0.747545   0.39019949]
2.0
